profile: normal  # cautious | normal | fast

profiles:
  cautious:
    cooldown_seconds: 4.0
    center_distance_offset: 0.5
    side_distance_offset: 0.5
    verbosity: high

  normal:
    cooldown_seconds: 3.0
    center_distance_offset: 0.0
    side_distance_offset: 0.0
    verbosity: medium

  fast:
    cooldown_seconds: 2.0
    center_distance_offset: -0.3
    side_distance_offset: -0.3
    verbosity: low
